---
driver:
  name: docker
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      roles_path: ${MOLECULE_PROJECT_DIRECTORY}/roles
  ansible_args:
    - "--skip-tags"
    - "${PROVISIONER_SKIP_TAGS:-hifiberry-only}"
  inventory:
    links:
      group_vars: ${MOLECULE_PROJECT_DIRECTORY}/environments/amsel/group_vars
  env:
    ANSIBLE_FORCE_COLOR: "True"
dependency:
  name: galaxy
verifier:
  name: ansible
